name: Bug Report
description: Create a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: What are the exact steps to reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
      
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      multiple: false
      options:
        - Chrome
        - Edge
        - Brave
        - Other Chromium-based browser
    validations:
      required: true
      
  - type: input
    id: browser-version
    attributes:
      label: Browser version
      placeholder: e.g. 119.0.6045.105
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
      
  - type: input
    id: extension-version
    attributes:
      label: Extension version
      placeholder: e.g. 1.0.0
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true